# This file is part of sconsUtils.
#
# Developed for the LSST Data Management System.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
cuda

CUDA Tool for SCons

"""

import os

import SCons.Defaults
import SCons.Scanner.C
import SCons.Tool

CUDAScanner = SCons.Scanner.C.CScanner()


# this object emitters add '.linkinfo' suffixed files as extra targets
# these files are generated by nvcc. The reason to do this is to remove
# the extra .linkinfo files when calling scons -c
def CUDANVCCStaticObjectEmitter(target, source, env):
    tgt, src = SCons.Defaults.StaticObjectEmitter(target, source, env)
    for file in src:
        lifile = os.path.splitext(src[0].rstr())[0] + ".linkinfo"  # noqa F841
        # tgt.append(lifile)
    return tgt, src


def CUDANVCCSharedObjectEmitter(target, source, env):
    tgt, src = SCons.Defaults.SharedObjectEmitter(target, source, env)
    for file in src:
        lifile = os.path.splitext(src[0].rstr())[0] + ".linkinfo"  # noqa F841
        # tgt.append(lifile)
    return tgt, src


def generate(env):
    staticObjBuilder, sharedObjBuilder = SCons.Tool.createObjBuilders(env)
    staticObjBuilder.add_action(".cu", "$STATICNVCCCMD")
    staticObjBuilder.add_emitter(".cu", CUDANVCCStaticObjectEmitter)
    sharedObjBuilder.add_action(".cu", "$SHAREDNVCCCMD")
    sharedObjBuilder.add_emitter(".cu", CUDANVCCSharedObjectEmitter)
    SCons.Tool.SourceFileScanner.add_scanner(".cu", CUDAScanner)

    # default compiler
    env["NVCC"] = "nvcc"

    # default flags for the NVCC compiler
    env["NVCCFLAGS"] = ""
    env["STATICNVCCFLAGS"] = ""
    env["SHAREDNVCCFLAGS"] = ""
    env["ENABLESHAREDNVCCFLAG"] = "-shared"
    env["NVCCCMDLINE"] = ""

    # default NVCC commands
    env["STATICNVCCCMD"] = (
        "$NVCC -o $TARGET -c $NVCCFLAGS $_CPPINCFLAGS $STATICNVCCFLAGS $NVCCCMDLINE $SOURCES"
    )
    env["SHAREDNVCCCMD"] = (
        "$NVCC -o $TARGET -c $NVCCFLAGS $_CPPINCFLAGS $SHAREDNVCCFLAGS"
        " $ENABLESHAREDNVCCFLAG $NVCCCMDLINE $SOURCES"
    )


def exists(env):
    return env.Detect("nvcc")
