name: build_and_test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test_conda:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true

      - name: Install conda packages used by this package
        shell: bash -l {0}
        run: |
          conda install -y -q scons eups compilers ruff flake8

      # We have two cores so we can speed up the testing with xdist
      - name: Install pytest packages
        shell: bash -l {0}
        run: |
          conda install -y -q \
            pytest pytest-xdist pytest-cov pytest-session2file

      - name: List installed packages
        shell: bash -l {0}
        run: |
          conda list
          pip list -v

      - name: Build and test
        shell: bash -l {0}
        run: |
          setup -k -r .
          scons -j2
          python -c 'import importlib.metadata as M; print(M.version("lsst.sconsUtils"))'

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v6
        with:
          files: tests/.tests/pytest-sconsUtils.xml-cov-sconsUtils.xml
          token: ${{ secrets.CODECOV_TOKEN }}
  build_and_test_pip:
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          # Need to clone everything for the git tags.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "setup.cfg"
          allow-prereleases: true

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install --upgrade pip uv
          uv pip install --system -r requirements.txt

      # We have two cores so we can speed up the testing with xdist
      - name: Install pytest packages
        shell: bash -l {0}
        run: |
          uv pip install --system pytest pytest-xdist

      - name: Build and install
        run: |
          uv pip install --system --no-deps -v -e .

      # One test should not be run by pytest because it relies on scons
      # setting environment variables.
      - name: Run tests
        run: |
          pytest --ignore=tests/test_run_by_scons.py -r a -v -n 3
          scons -j2

  check-changes:
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Check if weekly changed
        id: check
        run: |
          # Get SHA hashes for all weekly tags
          weekly_sha=$(git tag -l 'w.*' | while read tag; do
            git rev-list -n 1 "${tag}"
          done)

          echo "Weekly tag SHA ${weekly_sha}"
          # Extract the current tag and its SHA
          current_tag=${GITHUB_REF#refs/tags/}
          echo "Current tag: ${current_tag}"
          current_sha=$(git rev-list -1 "${current_tag}") || echo "no_value"
          echo "Current sha: ${current_sha}"
          # Count occurrences of the current SHA in the weekly SHA list
          n=$(echo "${weekly_sha}" | grep -c "${current_sha}") || echo "0"
          echo "Current tag ${current_tag} (${current_sha}) SHA found ${n} time(s)"

          # Determine whether to skip the upload based on the count
          if [ "${n}" -gt 1 ]; then
            echo "Skip upload"
            echo "skip=true" >> "${GITHUB_OUTPUT}"
          else
            echo "Enable upload"
            echo "skip=false" >> "${GITHUB_OUTPUT}"
          fi

  pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: [build_and_test_conda, build_and_test_pip, check-changes]
    permissions:
      id-token: write
    if: "${{ ! startsWith(github.ref, 'refs/tags/w.') || needs.check-changes.outputs.skip == 'false' }}"

    steps:
      - uses: actions/checkout@v6
        with:
          # Need to clone everything to embed the version.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel build

      - name: Build and create distribution
        run: |
          python -m build --skip-dependency-check

      - name: Upload
        uses: pypa/gh-action-pypi-publish@release/v1
