name: build_and_test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        pyversion: ["3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true

      - name: Install conda packages used by this package
        shell: bash -l {0}
        run: |
          conda install -y -q scons eups compilers ruff flake8

      # We have two cores so we can speed up the testing with xdist
      - name: Install pytest packages
        shell: bash -l {0}
        run: |
          conda install -y -q \
            pytest pytest-xdist pytest-cov pytest-session2file

      - name: List installed packages
        shell: bash -l {0}
        run: |
          conda list
          pip list -v

      - name: Build and test
        shell: bash -l {0}
        run: |
          setup -k -r .
          scons -j2
          python -c 'import importlib.metadata as M; print(M.version("lsst.sconsUtils"))'

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          files: tests/.tests/pytest-sconsUtils.xml-cov-sconsUtils.xml
          token: ${{ secrets.CODECOV_TOKEN }}
